{'data': [{'attributes': {'description': [],
                           'group': 'format',
                           'name': {'en': 'Oneshot'},
                           'version': 1},
            'id': '0234a31e-a729-4e28-9d6a-3f87c4966b9e',
            'relationships': [],
            'type': 'tag'},
           {'attributes': {'description': [],
                           'group': 'genre',
                           'name': {'en': 'Thriller'},
                           'version': 1},
            'id': '07251805-a27e-4d59-b488-f0bfbec15168',
            'relationships': [],
            'type': 'tag'},
           {'attributes': {'description': [],
                           'group': 'format',
                           'name': {'en': 'Award Winning'},
                           'version': 1},
            'id': '0a39b5a1-b235-4886-a747-1d05d216532d',
            'relationships': [],
            'type': 'tag'},
           {'attributes': {'description': [],
                           'group': 'theme',
                           'name': {'en': 'Reincarnation'},
                           'version': 1},
            'id': '0bc90acb-ccc1-44ca-a34a-b9f3a73259d0',
            'relationships': [],
            'type': 'tag'},
           {'attributes': {'description': [],
                           'group': 'genre',
                           'name': {'en': 'Sci-Fi'},
                           'version': 1},
            'id': '256c8bd9-4904-4360-bf4f-508a76d67183',
            'relationships': [],
            'type': 'tag'},
           {'attributes': {'description': [],
                           'group': 'theme',
                           'name': {'en': 'Time Travel'},
                           'version': 1},
            'id': '292e862b-2d17-4062-90a2-0356caa4ae27',
            'relationships': [],
            'type': 'tag'},
           {'attributes': {'description': [],
                           'group': 'theme',
                           'name': {'en': 'Genderswap'},
                           'version': 1},
            'id': '2bd2e8d0-f146-434a-9b51-fc9ff2c5fe6a',
            'relationships': [],
            'type': 'tag'},
           {'attributes': {'description': [],
                           'group': 'theme',
                           'name': {'en': 'Loli'},
                           'version': 1},
            'id': '2d1f5d56-a1e5-4d0d-a961-2193588b08ec',
            'relationships': [],
            'type': 'tag'},
           {'attributes': {'description': [],
                           'group': 'theme',
                           'name': {'en': 'Traditional Games'},
                           'version': 1},
            'id': '31932a7e-5b8e-49a6-9f12-2afa39dc544c',
            'relationships': [],
            'type': 'tag'},
           {'attributes': {'description': [],
                           'group': 'format',
                           'name': {'en': 'Official Colored'},
                           'version': 1},
            'id': '320831a8-4026-470b-94f6-8353740e6f04',
            'relationships': [],
            'type': 'tag'},
           {'attributes': {'description': [],
                           'group': 'genre',
                           'name': {'en': 'Historical'},
                           'version': 1},
            'id': '33771934-028e-4cb3-8744-691e866a923e',
            'relationships': [],
            'type': 'tag'},
           {'attributes': {'description': [],
                           'group': 'theme',
                           'name': {'en': 'Monsters'},
                           'version': 1},
            'id': '36fd93ea-e8b8-445e-b836-358f02b3d33d',
            'relationships': [],
            'type': 'tag'},
           {'attributes': {'description': [],
                           'group': 'genre',
                           'name': {'en': 'Action'},
                           'version': 1},
            'id': '391b0423-d847-456f-aff0-8b0cfc03066b',
            'relationships': [],
            'type': 'tag'},
           {'attributes': {'description': [],
                           'group': 'theme',
                           'name': {'en': 'Demons'},
                           'version': 1},
            'id': '39730448-9a5f-48a2-85b0-a70db87b1233',
            'relationships': [],
            'type': 'tag'},
           {'attributes': {'description': [],
                           'group': 'genre',
                           'name': {'en': 'Psychological'},
                           'version': 1},
            'id': '3b60b75c-a2d7-4860-ab56-05f391bb889c',
            'relationships': [],
            'type': 'tag'},
           {'attributes': {'description': [],
                           'group': 'theme',
                           'name': {'en': 'Ghosts'},
                           'version': 1},
            'id': '3bb26d85-09d5-4d2e-880c-c34b974339e9',
            'relationships': [],
            'type': 'tag'},
           {'attributes': {'description': [],
                           'group': 'theme',
                           'name': {'en': 'Animals'},
                           'version': 1},
            'id': '3de8c75d-8ee3-48ff-98ee-e20a65c86451',
            'relationships': [],
            'type': 'tag'},
           {'attributes': {'description': [],
                           'group': 'format',
                           'name': {'en': 'Long Strip'},
                           'version': 1},
            'id': '3e2b8dae-350e-4ab8-a8ce-016e844b9f0d',
            'relationships': [],
            'type': 'tag'},
           {'attributes': {'description': [],
                           'group': 'genre',
                           'name': {'en': 'Romance'},
                           'version': 1},
            'id': '423e2eae-a7a2-4a8b-ac03-a8351462d71d',
            'relationships': [],
            'type': 'tag'},
           {'attributes': {'description': [],
                           'group': 'theme',
                           'name': {'en': 'Ninja'},
                           'version': 1},
            'id': '489dd859-9b61-4c37-af75-5b18e88daafc',
            'relationships': [],
            'type': 'tag'},
           {'attributes': {'description': [],
                           'group': 'genre',
                           'name': {'en': 'Comedy'},
                           'version': 1},
            'id': '4d32cc48-9f00-4cca-9b5a-a839f0764984',
            'relationships': [],
            'type': 'tag'},
           {'attributes': {'description': [],
                           'group': 'genre',
                           'name': {'en': 'Mecha'},
                           'version': 1},
            'id': '50880a9d-5440-4732-9afb-8f457127e836',
            'relationships': [],
            'type': 'tag'},
           {'attributes': {'description': [],
                           'group': 'format',
                           'name': {'en': 'Anthology'},
                           'version': 1},
            'id': '51d83883-4103-437c-b4b1-731cb73d786c',
            'relationships': [],
            'type': 'tag'},
           {'attributes': {'description': [],
                           'group': 'genre',
 '                          \'name\': {\'en\': Boys\' Love},'
                           'version': 1},
            'id': '5920b825-4181-4a17-beeb-9918b0ff7a30',
            'relationships': [],
            'type': 'tag'},
           {'attributes': {'description': [],
                           'group': 'theme',
                           'name': {'en': 'Incest'},
                           'version': 1},
            'id': '5bd0e105-4481-44ca-b6e7-7544da56b1a3',
            'relationships': [],
            'type': 'tag'},
           {'attributes': {'description': [],
                           'group': 'genre',
                           'name': {'en': 'Crime'},
                           'version': 1},
            'id': '5ca48985-9a9d-4bd8-be29-80dc0303db72',
            'relationships': [],
            'type': 'tag'},
           {'attributes': {'description': [],
                           'group': 'theme',
                           'name': {'en': 'Survival'},
                           'version': 1},
            'id': '5fff9cde-849c-4d78-aab0-0d52b2ee1d25',
            'relationships': [],
            'type': 'tag'},
           {'attributes': {'description': [],
                           'group': 'theme',
                           'name': {'en': 'Zombies'},
                           'version': 1},
            'id': '631ef465-9aba-4afb-b0fc-ea10efe274a8',
            'relationships': [],
            'type': 'tag'},
           {'attributes': {'description': [],
                           'group': 'theme',
                           'name': {'en': 'Reverse Harem'},
                           'version': 1},
            'id': '65761a2a-415e-47f3-bef2-a9dababba7a6',
            'relationships': [],
            'type': 'tag'},
           {'attributes': {'description': [],
                           'group': 'genre',
                           'name': {'en': 'Sports'},
                           'version': 1},
            'id': '69964a64-2f90-4d33-beeb-f3ed2875eb4c',
            'relationships': [],
            'type': 'tag'},
           {'attributes': {'description': [],
                           'group': 'genre',
                           'name': {'en': 'Superhero'},
                           'version': 1},
            'id': '7064a261-a137-4d3a-8848-2d385de3a99c',
            'relationships': [],
            'type': 'tag'},
           {'attributes': {'description': [],
                           'group': 'theme',
                           'name': {'en': 'Martial Arts'},
                           'version': 1},
            'id': '799c202e-7daa-44eb-9cf7-8a3c0441531e',
            'relationships': [],
            'type': 'tag'},
           {'attributes': {'description': [],
                           'group': 'format',
                           'name': {'en': 'Fan Colored'},
                           'version': 1},
            'id': '7b2ce280-79ef-4c09-9b58-12b7c23a9b78',
            'relationships': [],
            'type': 'tag'},
           {'attributes': {'description': [],
                           'group': 'theme',
                           'name': {'en': 'Samurai'},
                           'version': 1},
            'id': '81183756-1453-4c81-aa9e-f6e1b63be016',
            'relationships': [],
            'type': 'tag'},
           {'attributes': {'description': [],
                           'group': 'genre',
                           'name': {'en': 'Magical Girls'},
                           'version': 1},
            'id': '81c836c9-914a-4eca-981a-560dad663e73',
            'relationships': [],
            'type': 'tag'},
           {'attributes': {'description': [],
                           'group': 'theme',
                           'name': {'en': 'Mafia'},
                           'version': 1},
            'id': '85daba54-a71c-4554-8a28-9901a8b0afad',
            'relationships': [],
            'type': 'tag'},
           {'attributes': {'description': [],
                           'group': 'genre',
                           'name': {'en': 'Adventure'},
                           'version': 1},
            'id': '87cc87cd-a395-47af-b27a-93258283bbc6',
            'relationships': [],
            'type': 'tag'},
           {'attributes': {'description': [],
                           'group': 'format',
                           'name': {'en': 'User Created'},
                           'version': 1},
            'id': '891cf039-b895-47f0-9229-bef4c96eccd4',
            'relationships': [],
            'type': 'tag'},
           {'attributes': {'description': [],
                           'group': 'theme',
                           'name': {'en': 'Virtual Reality'},
                           'version': 1},
            'id': '8c86611e-fab7-4986-9dec-d1a2f44acdd5',
            'relationships': [],
            'type': 'tag'},
           {'attributes': {'description': [],
                           'group': 'theme',
                           'name': {'en': 'Office Workers'},
                           'version': 1},
            'id': '92d6d951-ca5e-429c-ac78-451071cbf064',
            'relationships': [],
            'type': 'tag'},
           {'attributes': {'description': [],
                           'group': 'theme',
                           'name': {'en': 'Video Games'},
                           'version': 1},
            'id': '9438db5a-7e2a-4ac0-b39e-e0d95a34b8a8',
            'relationships': [],
            'type': 'tag'},
           {'attributes': {'description': [],
                           'group': 'theme',
                           'name': {'en': 'Post-Apocalyptic'},
                           'version': 1},
            'id': '9467335a-1b83-4497-9231-765337a00b96',
            'relationships': [],
            'type': 'tag'},
           {'attributes': {'description': [],
                           'group': 'content',
                           'name': {'en': 'Sexual Violence'},
                           'version': 1},
            'id': '97893a4c-12af-4dac-b6be-0dffb353568e',
            'relationships': [],
            'type': 'tag'},
           {'attributes': {'description': [],
                           'group': 'theme',
                           'name': {'en': 'Crossdressing'},
                           'version': 1},
            'id': '9ab53f92-3eed-4e9b-903a-917c86035ee3',
            'relationships': [],
            'type': 'tag'},
           {'attributes': {'description': [],
                           'group': 'theme',
                           'name': {'en': 'Magic'},
                           'version': 1},
            'id': 'a1f53773-c69a-4ce5-8cab-fffcd90b1565',
            'relationships': [],
            'type': 'tag'},
           {'attributes': {'description': [],
                           'group': 'genre',
 '                          \'name\': {\'en\': Girls\' Love},'
                           'version': 1},
            'id': 'a3c67850-4684-404e-9b7f-c69850ee5da6',
            'relationships': [],
            'type': 'tag'},
           {'attributes': {'description': [],
                           'group': 'theme',
                           'name': {'en': 'Harem'},
                           'version': 1},
            'id': 'aafb99c1-7f60-43fa-b75f-fc9502ce29c7',
            'relationships': [],
            'type': 'tag'},
           {'attributes': {'description': [],
                           'group': 'theme',
                           'name': {'en': 'Military'},
                           'version': 1},
            'id': 'ac72833b-c4e9-4878-b9db-6c8a4a99444a',
            'relationships': [],
            'type': 'tag'},
           {'attributes': {'description': [],
                           'group': 'genre',
                           'name': {'en': 'Wuxia'},
                           'version': 1},
            'id': 'acc803a4-c95a-4c22-86fc-eb6b582d82a2',
            'relationships': [],
            'type': 'tag'},
           {'attributes': {'description': [],
                           'group': 'genre',
                           'name': {'en': 'Isekai'},
                           'version': 1},
            'id': 'ace04997-f6bd-436e-b261-779182193d3d',
            'relationships': [],
            'type': 'tag'},
           {'attributes': {'description': [],
                           'group': 'format',
                           'name': {'en': '4-Koma'},
                           'version': 1},
            'id': 'b11fda93-8f1d-4bef-b2ed-8803d3733170',
            'relationships': [],
            'type': 'tag'},
           {'attributes': {'description': [],
                           'group': 'format',
                           'name': {'en': 'Doujinshi'},
                           'version': 1},
            'id': 'b13b2a48-c720-44a9-9c77-39c9979373fb',
            'relationships': [],
            'type': 'tag'},
           {'attributes': {'description': [],
                           'group': 'genre',
                           'name': {'en': 'Philosophical'},
                           'version': 1},
            'id': 'b1e97889-25b4-4258-b28b-cd7f4d28ea9b',
            'relationships': [],
            'type': 'tag'},
           {'attributes': {'description': [],
                           'group': 'content',
                           'name': {'en': 'Gore'},
                           'version': 1},
            'id': 'b29d6a3d-1569-4e7a-8caf-7557bc92cd5d',
            'relationships': [],
            'type': 'tag'},
           {'attributes': {'description': [],
                           'group': 'genre',
                           'name': {'en': 'Drama'},
                           'version': 1},
            'id': 'b9af3a63-f058-46de-a9a0-e0c13906197a',
            'relationships': [],
            'type': 'tag'},
           {'attributes': {'description': [],
                           'group': 'genre',
                           'name': {'en': 'Medical'},
                           'version': 1},
            'id': 'c8cbe35b-1b2b-4a3f-9c37-db84c4514856',
            'relationships': [],
            'type': 'tag'},
           {'attributes': {'description': [],
                           'group': 'theme',
                           'name': {'en': 'School Life'},
                           'version': 1},
            'id': 'caaa44eb-cd40-4177-b930-79d3ef2afe87',
            'relationships': [],
            'type': 'tag'},
           {'attributes': {'description': [],
                           'group': 'genre',
                           'name': {'en': 'Horror'},
                           'version': 1},
            'id': 'cdad7e68-1419-41dd-bdce-27753074a640',
            'relationships': [],
            'type': 'tag'},
           {'attributes': {'description': [],
                           'group': 'genre',
                           'name': {'en': 'Fantasy'},
                           'version': 1},
            'id': 'cdc58593-87dd-415e-bbc0-2ec27bf404cc',
            'relationships': [],
            'type': 'tag'},
           {'attributes': {'description': [],
                           'group': 'theme',
                           'name': {'en': 'Villainess'},
                           'version': 1},
            'id': 'd14322ac-4d6f-4e9b-afd9-629d5f4d8a41',
            'relationships': [],
            'type': 'tag'},
           {'attributes': {'description': [],
                           'group': 'theme',
                           'name': {'en': 'Vampires'},
                           'version': 1},
            'id': 'd7d1730f-6eb0-4ba6-9437-602cac38664c',
            'relationships': [],
            'type': 'tag'},
           {'attributes': {'description': [],
                           'group': 'theme',
                           'name': {'en': 'Delinquents'},
                           'version': 1},
            'id': 'da2d50ca-3018-4cc0-ac7a-6b7d472a29ea',
            'relationships': [],
            'type': 'tag'},
           {'attributes': {'description': [],
                           'group': 'theme',
                           'name': {'en': 'Monster Girls'},
                           'version': 1},
            'id': 'dd1f77c5-dea9-4e2b-97ae-224af09caf99',
            'relationships': [],
            'type': 'tag'},
           {'attributes': {'description': [],
                           'group': 'theme',
                           'name': {'en': 'Shota'},
                           'version': 1},
            'id': 'ddefd648-5140-4e5f-ba18-4eca4071d19b',
            'relationships': [],
            'type': 'tag'},
           {'attributes': {'description': [],
                           'group': 'theme',
                           'name': {'en': 'Police'},
                           'version': 1},
            'id': 'df33b754-73a3-4c54-80e6-1a74a8058539',
            'relationships': [],
            'type': 'tag'},
           {'attributes': {'description': [],
                           'group': 'format',
                           'name': {'en': 'Web Comic'},
                           'version': 1},
            'id': 'e197df38-d0e7-43b5-9b09-2842d0c326dd',
            'relationships': [],
            'type': 'tag'},
           {'attributes': {'description': [],
                           'group': 'genre',
                           'name': {'en': 'Slice of Life'},
                           'version': 1},
            'id': 'e5301a23-ebd9-49dd-a0cb-2add944c7fe9',
            'relationships': [],
            'type': 'tag'},
           {'attributes': {'description': [],
                           'group': 'theme',
                           'name': {'en': 'Aliens'},
                           'version': 1},
            'id': 'e64f6742-c834-471d-8d72-dd51fc02b835',
            'relationships': [],
            'type': 'tag'},
           {'attributes': {'description': [],
                           'group': 'theme',
                           'name': {'en': 'Cooking'},
                           'version': 1},
            'id': 'ea2bc92d-1c26-4930-9b7c-d5c0dc1b6869',
            'relationships': [],
            'type': 'tag'},
           {'attributes': {'description': [],
                           'group': 'theme',
                           'name': {'en': 'Supernatural'},
                           'version': 1},
            'id': 'eabc5b4c-6aff-42f3-b657-3e90cbd00b75',
            'relationships': [],
            'type': 'tag'},
           {'attributes': {'description': [],
                           'group': 'genre',
                           'name': {'en': 'Mystery'},
                           'version': 1},
            'id': 'ee968100-4191-4968-93d3-f82d72be7e46',
            'relationships': [],
            'type': 'tag'},
           {'attributes': {'description': [],
                           'group': 'format',
                           'name': {'en': 'Adaptation'},
                           'version': 1},
            'id': 'f4122d1c-3b44-44d0-9936-ff7502c39ad3',
            'relationships': [],
            'type': 'tag'},
           {'attributes': {'description': [],
                           'group': 'theme',
                           'name': {'en': 'Music'},
                           'version': 1},
            'id': 'f42fbf9e-188a-447b-9fdc-f19dc1e4d685',
            'relationships': [],
            'type': 'tag'},
           {'attributes': {'description': [],
                           'group': 'format',
                           'name': {'en': 'Full Color'},
                           'version': 1},
            'id': 'f5ba408b-0e7a-484d-8d49-4e9125ac96de',
            'relationships': [],
            'type': 'tag'},
           {'attributes': {'description': [],
                           'group': 'genre',
                           'name': {'en': 'Tragedy'},
                           'version': 1},
            'id': 'f8f62932-27da-4fe4-8ee1-6779a8c5edba',
            'relationships': [],
            'type': 'tag'},
           {'attributes': {'description': [],
                           'group': 'theme',
                           'name': {'en': 'Gyaru'},
                           'version': 1},
            'id': 'fad12b5e-68ba-460e-b933-9ae8318f5b65',
            'relationships': [],
            'type': 'tag'}],
  'limit': 76,
  'offset': 0,
  'response': 'collection',
  'result': 'ok',
  'total': 76}